import OpenAI from "openai";
import { ParsedSpec } from "./parser.js";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

/**
 * Represents the three files generated by the AI
 * for a given feature spec.
 */
export interface GeneratedFiles {
  controller: string;
  service: string;
  tests: string;
}

/**
 * Sends the parsed spec to OpenAI and returns
 * generated TypeScript code as structured files.
 *
 * @param spec - the parsed spec object from parser.ts
 * @returns GeneratedFiles containing controller, service, and test code
 */
export async function generateCode(spec: ParsedSpec): Promise<GeneratedFiles> {
  console.log("Calling AI to generate code...");

  const systemPrompt = `
You are a senior TypeScript developer helping scaffold a new feature.
Given the spec below, generate production-ready TypeScript code.

Feature: ${spec.title}
Requirements:
${spec.bullets.map((b) => `- ${b}`).join("\n")}

Respond ONLY in this exact JSON format, no markdown, no explanation:
{
  "controller": "// controller code here as a string",
  "service": "// service code here as a string",
  "tests": "// vitest test code here as a string"
}
`;

  try {
    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: systemPrompt }],
      response_format: { type: "json_object" },
    });

    const responseText = response.choices[0].message.content ?? "";

    // if openai returns an empty response, stop early
    if (!responseText) {
      console.error("AI returned an empty response. Try again.");
      process.exit(1);
    }

    const parsed = JSON.parse(responseText);
    return parsed;
  } catch (error: any) {
    // handle specific openai error types with clear messages
    if (error?.status === 401) {
      console.error("Invalid OpenAI API key. Check your .env file.");
    } else if (error?.status === 429) {
      console.error("OpenAI rate limit hit. Wait a moment and try again.");
    } else if (error?.status === 500) {
      console.error("OpenAI server error. Try again in a few minutes.");
    } else {
      console.error("Something went wrong calling the AI:", error?.message);
    }
    process.exit(1);
  }
}
